Project/netsetshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

Project/netsetshop/netsetshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('onlineshop/', include('onlineshop.urls', namespace = 'onlineshop')),
    path('', include('onlineshop.urls', namespace = 'home')),

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,
                        document_root = settings.MEDIA_ROOT)

Project/netsetshop/onlineshop/urls.py
from django.urls import path 
from django.urls import path, include
from . import views

app_name = 'onlineshop'

urlpatterns = [ 
            path('', views.product_list,name = 'product_list'),
            path('<slug:category_slug>/', views.product_list, name = 'product_list_by_category'),
            path('<int:id>/<slug:slug>/' ,views.product_detail,name=' product_detail'),
            path('' ,include('onlineshop.urls', namespace='home')),

            ]

Project/netsetshop/cart/models.py
from django.db import models

# Create your models here.

Project/netsetshop/onlineshop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
            ordering = ('name',)
            verbose_name = 'category'
            verbose_name_plural = 'categories'
    def __str__(self):
          return self.name
          
    def get_absolute_url(self):
        return reverse('onlineshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/m/%d',blank=True)
    description = models.TextField(blank = True, null = True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
            ordering = ('name',)
            index_together = (('id','slug'),)
            
    def __str__(self):
          return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_detail', args=[self.id, self.slug])

Project/netsetshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Project/netsetshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from onlineshop.models import Product
from .cart import Cart
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request, product_id):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial = {'quantity':item['quantity'], 'override':True})
    return render(request, 'cart/detail.html', {'cart':cart})

Project/netsetshop/onlineshop/views.py
from django.shortcuts import render, get_object_or_404
from.models import Category, Product
from cart.forms import CartAddProductForm
from django.http import HttpResponse

def home(request):
    return render(request, 'onlineshop/product/home.html')

def AboutUs(request):
    return render(request, 'AboutUs.html')
# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)

    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category = category)
    return render(request, 'onlineshop/product/list.html',{
         'category': category,
        'categories': categories,
        'products':products,
        })

def product_detail(request, id, slug):
    product= get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 
    'onlineshop/product/detail.html',
    {'product':product,'cart_product_form':cart_product_form})

Project/netsetshop/cart/templates/cart/detail.html
{% extends onlineshop/base.html %}
{% load static %}

{% block title %}
  Shopping Cart
{% endblock %}

{% block content %}
<h1>Shopping Cart</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Remove</th>
      <th>Unit Price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
    {% with product = item.product %}
    <tr>
      <td>
        <a href="{{product.get_absolute_url}}">
          <img src = "{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}"{% endif %}>
        </a>
      </td>
      <td>{{ product.name }}</td>
      <td>
            <form action = "{% url "cart:cart_add" product.id %}" method = "post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type = "submit" value = "Update">
                {% csrf_token %}
            </form>
        </td>
      <td>
        <form action="{% url "cart:cart_remove" product.id %}" method="post">
          <input type="submit" value="Remove">
          {% csrf_token %}
        </form>
      </td>
      <td>${{ item.price }}</td>
      <td>${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class='total'>
      <td>Total</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url 'onlineshop:product_list' %}" class="buttonlight">Continue Shopping</a>
  <a href="#" class="button">Checkout</a>
</p>
{% endblock %}

Project/netsetshop/onlineshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">My Shop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
        {% if total_items > 0 %}
        Your Cart:
        <a href = "{% url "cart:cart_detail" %}">
          {{ total_items }} item{{total_items|pluralize }}
        </a>
        {% else %}
        Your Cart is Empty
        {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

Project/netsetshop/onlineshop/templates/onlineshop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  
  <body>
    <div id="header">
      <a href="/" class="logo">My Shop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        Your cart is empty
      </div>
    </div>
    <div id="content">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

Project/netsetshop/onlineshop/templates/onlineshop/product/AboutUs.html
<!DOCTYPE html>
<html>
<head>
    <title>About Us</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" href= "style.css"> <!--style will get applied proparly-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container">
            <div class="navbar">
                    <div class="icon">
                        <h2 class="logo">SPARK </h2>
                    </div>
                       <div class="menu">
                            <ul>

                                <li><a href="home.html">HOME</a></li>
                                <li> <a href="news.html">NEWS</a></li>
                                <li><a href="contactUs.html">CONTACT</a></li>
                                <li><a class =active href="AboutUs.html">ABOUT</a></li>
                                <li><a href="shoppingCart.html">CART</a></li>
                                
                            </ul>
                       </div>
                       <div class="search">
                        <form action="search.html">
                            <input class = "searchbtn" type="text" placeholder="Search.." name="search">
                            <a href="#"> <button class = "submitbtn" type="submit">Submit</button></a>
                          </form>
                       </div>
            </div>
			<br>
			<h1 style="text-align:center; color:rgb(21, 0, 255);">About Us</h1>
			<br>
			<p style="color:rgb(255, 255, 255); background-color:rgba(5, 1, 40, 0.636); text-align:center;">We are the team that founded Spark! We are committed to providing 
			each customer with excellent customer service<br> and providing all the latest and greatest electronic needs.
			We strive to make sure every product we offer <br>is the lowest price offered veruses our competitors, that 
			if it isn't, we will price match any offer!</p>
			<br>
			<h1 style="text-align:center; color:rgb(21, 0, 255);">Our Team</h2>
			<br><br><br><br>
			<div class="row">
				<div class="Acolumn">
					<div class="card">
						<img src="Images/Saja.jpg" alt="Saja" style="width:100%" style="height:80%">
						<h1 style="text-align:center; color:rgba(0, 225, 255, 0.988)">Saja Alallao</h1>
						<p class="title">CEO & Founder</p>
						<p>SDSU College of Engineering</p>
						<a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>	
						<p><button>Contact</button></p>
					  </div>
				</div>
			
				<div class="Acolumn">
					<div class="card">
						<img src="Images/Ezra.jpg" alt="Ezra" style="width:100%" >
						<h1 style="text-align:center; color:rgb(0, 225, 255, 0.988)">Ezra</h1>
						<p class="title">CEO & Founder</p>
						<p>SDSU College of Engineering</p>
						<a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>

						<p><button>Contact</button></p>
					  </div>
				</div>
				
				<div class="Acolumn">
					<div class="card">
						<img src="Images/r.jpg" alt="Ryan" style="width:100%" style="height:80%">
						<h1 style="text-align:center; color:rgba(0, 225, 255, 0.988)">Ryan Tran</h1>
						<p class="title">CEO & Founder, Ryan</p>
						<p>SDSU College of Engineering</p>
						<a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>
						<p><button>Contact</button></p>
					  </div>
				</div>
			</div>

          
          
	</div>
    
	<style>
		.card {
			box-shadow: 0 4px 8px 0 rgba(255, 255, 255, 0.426);
			max-width: 300px;
			margin: auto;
			text-align: center;
			}

			.title {
			color: rgb(255, 255, 255);
			font-size: 18px;
			}

			button {
			border: none;
			outline: 0;
			display: inline-block;
			padding: 8px;
			color: white;
			background-color: #000;
			text-align: center;
			cursor: pointer;
			width: 100%;
			font-size: 18px;
			}

			.a {
			text-decoration: none;
			font-size: 22px;
			color: rgb(1, 43, 255);
			}

			button:hover, a:hover {
			opacity: 0.5;
			}
		    footer {
			text-align: center;
			padding: 5px;
			background-color: rgba(222, 222, 234, 0.514);
			color: rgba(255, 0, 0, 0.178);
			font-style:normal; 
			
       	 }
	</style>
	 
      
      
       
</body>
 
<footer>
	<p style="color: blue;">SPARK<br>
	  For Any Complain Contact Our Co Founder Directly : <a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>	<br>
	<a href="mailto:hege@example.com"> &copy; Copyright 2022 HTML.am</a></p>
  </footer>
</html> 

Project/netsetshop/onlineshop/templates/onlineshop/product/Checkout.html
<!DOCTYPE html>
<html>
    <head>
        <title>SPARK</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styleCart.css">
        <link rel= "stylesheet" href="style.css"> <!--style will get applied proparly-->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <div class="icon">
                    <h2 class="logo">SPARK </h2>
                </div>
                <div class="menu">
                    <ul>
                        <li><a href="home.html">HOME</a></li>
                        <li><a href="news.html">NEWS</a></li>
                        <li><a href="contactUs.html">CONTACT</a></li>
                        <li><a href="AboutUs.html">ABOUT</a></li>
                        <li><a href="shoppingCart.html">CART</a></li>
                    </ul>
                </div>
                <div class="search">
                    <form action="search.html">
                        <input class = "searchbtn" type="text" placeholder="Search.." name="search">
                        <a href="#"><button class = "submitbtn" type="submit">Submit</button></a>
                    </form>
                </div>
            </div>
            <div class="container">
                <div class="titleHeader">
                    <h1>Checkout</h1>
                </div>
                <div class="row">
                    <div class="columnBill">
                        <div class="checkout">
                            <div class="billingInfo">
                                <h3>Billing Information</h3>
                                <form action="">
                                    <div class="row">
                                        <div class="column">
                                            <label>First name</label>
                                            <br>
                                            <input type="text" id="firstName" placeholder="John" required>
                                        </div>
                                        <div class="column">
                                            <label>Last name</label>
                                            <br>
                                            <input type="text" id="lastName" placeholder="Doe" required>
                                        </div>
                                    </div>
                                    <div class="email">
                                        <label>Email</label>
                                        <br>
                                        <input type="text" class="input" id="email" placeholder="you@email.com" required>
                                    </div>
                                    <div class="address">
                                        <label>Address</label>
                                        <br>
                                        <input type="text" class="input" id="address" placeholder="1234 Main St" required>
                                    </div>
                                    <div class="row">
                                        <div class="columnA">
                                            <div class="country">
                                                <label>Country</label>
                                                <br>
                                                <input type="text" class="inputCountry" id="country" placeholder="United States" required>
                                            </div>
                                        </div>
                                        <div class="columnB">
                                            <div class="State">
                                                <label>State</label>
                                                <br>
                                                <input type="text" class="inputState" id="state" placeholder="CA" required>
                                            </div>
                                        </div>
                                        <div class="columnB">
                                            <div class="zip">
                                                <label>Zip</label>
                                                <br>
                                                <input type="text" class="inputZip" id="firstName" placeholder="12345" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="shippingAddress">
                                        <input type="checkbox" class="shipAddress" id="sameAddress">
                                        <label id="sameAddress">Shipping address is the same as my billing address</label>
                                    </div>
                                    <h3>Delivery method</h3>
                                    <div class="delivery">
                                        <input type="radio" name="payment" value="standard" checked>
                                        <label>U.S. Standard</label>
                                        <small class="priceDeliv1">$0.00</small><br>
                                        <small>Currently 5-7 business days, unless otherwise noted.</small><br>
                                        <input type="radio" name="payment" value="2Day">
                                        <label>U.S. 2-Day Express</label>
                                        <small class="priceDeliv2">+$10.55</small><br>
                                        <small>2 business days if ordered by 10 AM PST.</small><br>
                                        <input type="radio" name="payment" value="nextDay">
                                        <label>U.S. Next Day Express</label>
                                        <small class="priceDeliv3">+$15.55</small><br>
                                        <small>Next business day if ordered by 10 AM PST.</small><br>
                                    </div>
                                    <h3>Payment</h3>
                                    <div class="payment">
                                        <input type="radio" name="payment" value="credit">
                                        <label>Credit card</label><br>
                                        <input type="radio" name="payment" value="debit">
                                        <label>Debit card</label><br>
                                        <input type="radio" name="payment" value="paypal">
                                        <label>Paypal</label>
                                    </div>
                                    <div class="row">
                                        <div class="column">
                                            <label>Name on card</label>
                                            <br>
                                            <input type="text" id="cardName" placeholder="John Doe" required>
                                            <br>
                                            <small class="cardDiscrip">Full name as displayed on card</small>
                                        </div>
                                        <div class="column">
                                            <label>Card number</label>
                                            <br>
                                            <input type="text" class="cardNum" id="cardNumber" placeholder="1234567812345678" required>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="columnC">
                                            <label>Expiration</label>
                                            <br>
                                            <input type="text" class="cardExp" id="cardExpiration" placeholder="01/27" required>
                                        </div>
                                        <div class="columnC">
                                            <label>CVV</label>
                                            <br>
                                            <input type="text" class="cardCvv" id="cardCVV" placeholder="123" required>
                                        </div>
                                    </div>
                                    <div class="backHome">
                                        <a href="home.html"><button type="button" class="contShopping">Continue shopping</button></a>
                                    </div>
                                    <div class="order">
                                        <a href="home.html"><button type="submit" id="order" class="cartOrder" onclick="alert('Your order has been placed.')">Order</button></a>
                                    </div>
                                </form>
                            </div>  
                        </div>
                    </div>
                    <div class="columnSummary">
                        <div class="summary2">
                            <h3>Summary</h3>
                            <div class="summaryItem">
                                <span class="text">Subtotal</span>
                                <span class="price">$3298</span>
                            </div>
                            <div class="summaryItem">
                                <span class="text">Discount</span>
                                <span class="price">$0.00</span>
                            </div>
                            <div class="summaryItem">
                                <span class="text">Shipping</span>
                                <span class="price">$5.95</span>
                            </div>
                            <div class="summaryItem">
                                <span class="text">Sales Tax</span>
                                <span class="price">$263.84</span>
                            </div>
                            <div class="summaryItem">
                                <span class="text">Total</span>
                                <span class="price">$3567.79</span>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <p class="mt-5 mb-3 text-muted" style="color:black; text-align:center">&copy; 2017–2022</p>
        </div>
    </body>
    
    <style>
         footer {
            text-align: center;
			padding: 5px;
            background-image: linear-gradient(to right, rgba(0, 132, 121, 0), rgb(67, 145, 123));
			color: rgba(255, 255, 255, 0.178);
			font-style:normal; 
			
        }
        </style>
      
      
        
        <footer>
          <p style="color: rgb(38, 37, 44);">SPARK<br>
            <b>For Any Complain Contact Our Co Founder Directly :</b> <a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>	<br>
          <a href="mailto:hege@example.com"> &copy; Copyright 2022 HTML.am</a></p>
        </footer>
         
</html>

Project/netsetshop/onlineshop/templates/onlineshop/product/ContactUsSent.html
<!DOCTYPE html>
<html>
<head>
    <title>SPARK</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" href= "style.css"> <!--style will get applied proparly-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <div class="container">
            <div class="navbar">
                    <div class="icon">
                        <h2 class="logo">SPARK </h2>
                    </div>
                       <div class="menu">
                            <ul>
                                
                                <li><a href="home.html">HOME</a></li>
                                <li> <a href="news.html">NEWS</a></li>
                                <li><a lass =active href="contactUs.html">CONTACT</a></li>
                                <li><a href="AboutUs.html">ABOUT</a></li>
                                <li><a href="shoppingCart.html">CART</a></li>
                            
                            </ul>
                       </div>
                       <div class="search">
                        <form action="search.html">
                            <input class = "searchbtn" type="text" placeholder="Search.." name="search">
                            <a href="#"> <button class = "submitbtn" type="submit">Submit</button></a>
                          </form>
                       </div>
            </div>
			<br><br><br><br>
			<h1 style="background-color:white; color:black; text-align:center;">Thank you for your submission!</h1>
			<h2 style="background-color:white; color:black; text-align:center;">One of our representatives will get 
			back to you as soon as possible!</h2>

            
          

    </div>
    

</body>
</html> 

Project/netsetshop/onlineshop/templates/onlineshop/product/detail.html
{% extends "onlineshop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{%static "img/no_image.png" %}{% endif %}">
    <h1>
      {{ product.name }}
    </h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">
      {{ product.price }}$
    </p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart" />
    </form>

  </div>
{% endblock %}

Project/netsetshop/onlineshop/templates/onlineshop/product/index.html
<!DOCTYPE html>
<html>
<head>
    <title>SPARK</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" href= "style.css"> <!--style will get applied proparly-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    

</head>
<body>
    <div class="container">
            <div class="navbar">
                    <div class="icon">
                        <h2 class="logo">SPARK </h2>
                    </div>
                       <div class="menu">
                            <ul>

                                <li><a class =active  href="home.html">HOME</a></li>
                                <li> <a href="news.html">NEWS</a></li>
                                <li><a href="contactUs.html">CONTACT</a></li>
                                <li><a href="AboutUs.html">ABOUT</a></li>
                                <li><a href="shoppingCart.html">CART</a></li>
                                
                            </ul>
                       </div>
                       <div class="search">
                        <form action="search.html">
                            <input class = "searchbtn" type="text" placeholder="Search.." name="search">
                            <a href="#"> <button class = "submitbtn" type="submit">Submit</button></a>
                          </form>
                       </div>
                       
            </div>

            
          

    </div>
    

    <style>
        footer {
          text-align: center;
          padding: 5px;
          background-color: rgb(0, 16, 70);
          color: rgba(0, 0, 0, 0);
          font-style:normal; 
        }
        </style>
      
      
        
        <footer>
          <p>SPARK<br>
            For Any Complain Contact Our Co Founder Directly : <a href="https://www.linkedin.com/in/saja-a/"><i class="fa fa-linkedin"></i></a>	<br>
          <a href="mailto:hege@example.com"> &copy; Copyright 2022 HTML.am</a></p>
        </footer>
         
</body>
</html> 

Project/netsetshop/onlineshop/templates/onlineshop/product/list.html
{% extends "onlineshop/base.html"%}
{% load static %}
{% block title%}
{% if category%} {{ category.name}}{% else %}Products{% endif %}
{% endblock %}
{% block content%}
<div id="sidebar">
    <h3> Categories </h3>
    <ul>
        <li {% if not category%} class="selected "{%endif%}>

            <a href="{% url 'onlineshop:product_list' %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected "{% endif %}>

            <a href="{{ c.get_absolute_url}}">{{c.name}}</a>
        </li>
        {% endfor %}
    </ul>    
</div>
<div>
    <div id="main" class="product-list">
        <h1 >{% if category %}{{category.name}}{% else %}Producst{%endif%}</h1>
        
        {% for product in product%}
        <div class="item">
            <a href="{{product.get_absolute_url}}">
            <img src="{% if product.image%}{{product.image.url}}{% else %}{% static "img/no_img.png" %} {% endif%}" >
            </a>
            <a href="{{product.get_absolute_url}}">{{product.name}}</a>
            <br>
            US Dollar{{product.price}}

        </div>
        {%endfor%}
    </div>
</div>
{% endblock content%}